name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: MinecraftLetsPlay
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Move files to assets
        run: |
          mkdir -p assets
          mv dist/* assets/

      - name: Commit and push snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: "chore: update snake animation"
          add: "assets/*"
